// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Letter_Type int32

const (
	Letter_Single Letter_Type = 0
	Letter_Group  Letter_Type = 1
	Letter_Ping   Letter_Type = 2
)

var Letter_Type_name = map[int32]string{
	0: "Single",
	1: "Group",
	2: "Ping",
}

var Letter_Type_value = map[string]int32{
	"Single": 0,
	"Group":  1,
	"Ping":   2,
}

func (x Letter_Type) String() string {
	return proto.EnumName(Letter_Type_name, int32(x))
}

func (Letter_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1, 0}
}

type Ticket struct {
	ConnID               string   `protobuf:"bytes,1,opt,name=connID,proto3" json:"connID,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ticket) Reset()         { *m = Ticket{} }
func (m *Ticket) String() string { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()    {}
func (*Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Ticket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ticket.Unmarshal(m, b)
}
func (m *Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ticket.Marshal(b, m, deterministic)
}
func (m *Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket.Merge(m, src)
}
func (m *Ticket) XXX_Size() int {
	return xxx_messageInfo_Ticket.Size(m)
}
func (m *Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket proto.InternalMessageInfo

func (m *Ticket) GetConnID() string {
	if m != nil {
		return m.ConnID
	}
	return ""
}

func (m *Ticket) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Letter struct {
	Type                 Letter_Type `protobuf:"varint,1,opt,name=type,proto3,enum=message.Letter_Type" json:"type,omitempty"`
	Receiver             string      `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Data                 []byte      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Letter) Reset()         { *m = Letter{} }
func (m *Letter) String() string { return proto.CompactTextString(m) }
func (*Letter) ProtoMessage()    {}
func (*Letter) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Letter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Letter.Unmarshal(m, b)
}
func (m *Letter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Letter.Marshal(b, m, deterministic)
}
func (m *Letter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Letter.Merge(m, src)
}
func (m *Letter) XXX_Size() int {
	return xxx_messageInfo_Letter.Size(m)
}
func (m *Letter) XXX_DiscardUnknown() {
	xxx_messageInfo_Letter.DiscardUnknown(m)
}

var xxx_messageInfo_Letter proto.InternalMessageInfo

func (m *Letter) GetType() Letter_Type {
	if m != nil {
		return m.Type
	}
	return Letter_Single
}

func (m *Letter) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *Letter) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Reply struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	HMAC                 []byte   `protobuf:"bytes,2,opt,name=HMAC,proto3" json:"HMAC,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp            int32    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Reply) GetHMAC() []byte {
	if m != nil {
		return m.HMAC
	}
	return nil
}

func (m *Reply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Reply) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Data struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp            int32    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Data) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("message.Letter_Type", Letter_Type_name, Letter_Type_value)
	proto.RegisterType((*Ticket)(nil), "message.Ticket")
	proto.RegisterType((*Letter)(nil), "message.Letter")
	proto.RegisterType((*Reply)(nil), "message.Reply")
	proto.RegisterType((*Data)(nil), "message.Data")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x4d, 0x37, 0xad, 0xdb, 0x61, 0x95, 0x32, 0x2c, 0x52, 0xc4, 0x43, 0xe9, 0xc5, 0x9e,
	0x7a, 0x50, 0xf0, 0x2e, 0x2e, 0xa8, 0xa0, 0xb0, 0xc4, 0x7d, 0x81, 0xda, 0x1d, 0x4a, 0xd8, 0x6d,
	0x12, 0xd2, 0x28, 0xf4, 0x19, 0x7c, 0x69, 0x69, 0xda, 0x55, 0x10, 0xf5, 0x36, 0xdf, 0x64, 0xe6,
	0xfb, 0x19, 0x02, 0x27, 0x2d, 0x75, 0x5d, 0xd5, 0x50, 0x69, 0xac, 0x76, 0x1a, 0x8f, 0x27, 0xcc,
	0x6f, 0x20, 0xda, 0xc8, 0x7a, 0x47, 0x0e, 0xcf, 0x20, 0xaa, 0xb5, 0x52, 0x8f, 0xab, 0x94, 0x65,
	0xac, 0x88, 0xc5, 0x44, 0xb8, 0x84, 0xd0, 0xe9, 0x1d, 0xa9, 0x34, 0xf0, 0xed, 0x11, 0xf2, 0x0f,
	0x06, 0xd1, 0x13, 0x39, 0x47, 0x16, 0x0b, 0xe0, 0xae, 0x37, 0xe4, 0xd7, 0x4e, 0xaf, 0x96, 0xe5,
	0x21, 0x69, 0x7c, 0x2e, 0x37, 0xbd, 0x21, 0xe1, 0x27, 0xf0, 0x1c, 0xe6, 0x96, 0x6a, 0x92, 0xef,
	0x64, 0x27, 0xdb, 0x17, 0x23, 0x02, 0xdf, 0x56, 0xae, 0x4a, 0x67, 0x19, 0x2b, 0x16, 0xc2, 0xd7,
	0xf9, 0x25, 0xf0, 0x61, 0x1b, 0x01, 0xa2, 0x17, 0xa9, 0x9a, 0x3d, 0x25, 0x47, 0x18, 0x43, 0x78,
	0x6f, 0xf5, 0x9b, 0x49, 0x18, 0xce, 0x81, 0xaf, 0xa5, 0x6a, 0x92, 0x20, 0x27, 0x08, 0x05, 0x99,
	0x7d, 0x3f, 0x1c, 0xd1, 0x91, 0xda, 0x92, 0x3d, 0x1c, 0x31, 0xd2, 0x60, 0x7f, 0x78, 0xbe, 0xbd,
	0xf3, 0xa9, 0x0b, 0xe1, 0xeb, 0xdf, 0x12, 0xf1, 0x02, 0x62, 0x27, 0x5b, 0xea, 0x5c, 0xd5, 0x9a,
	0x94, 0x67, 0xac, 0x08, 0xc5, 0x77, 0x23, 0x5f, 0x03, 0x5f, 0x0d, 0x53, 0xff, 0xa4, 0x78, 0x63,
	0xf0, 0x97, 0x71, 0xf6, 0xc3, 0xf8, 0x1a, 0xf9, 0xef, 0xb8, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff,
	0xd1, 0xb3, 0xb0, 0x0d, 0x9f, 0x01, 0x00, 0x00,
}
