// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/message.proto

package gschub

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Letter_Type int32

const (
	Letter_Single Letter_Type = 0
	Letter_Group  Letter_Type = 1
	Letter_Ping   Letter_Type = 2
	Letter_Rename Letter_Type = 3
)

var Letter_Type_name = map[int32]string{
	0: "Single",
	1: "Group",
	2: "Ping",
	3: "Rename",
}

var Letter_Type_value = map[string]int32{
	"Single": 0,
	"Group":  1,
	"Ping":   2,
	"Rename": 3,
}

func (x Letter_Type) String() string {
	return proto.EnumName(Letter_Type_name, int32(x))
}

func (Letter_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ebceca9e8703e37f, []int{7, 0}
}

type PublicKey struct {
	E                    string   `protobuf:"bytes,1,opt,name=E,proto3" json:"E,omitempty"`
	N                    string   `protobuf:"bytes,2,opt,name=N,proto3" json:"N,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKey) Reset()         { *m = PublicKey{} }
func (m *PublicKey) String() string { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()    {}
func (*PublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebceca9e8703e37f, []int{0}
}

func (m *PublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKey.Unmarshal(m, b)
}
func (m *PublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKey.Marshal(b, m, deterministic)
}
func (m *PublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKey.Merge(m, src)
}
func (m *PublicKey) XXX_Size() int {
	return xxx_messageInfo_PublicKey.Size(m)
}
func (m *PublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKey proto.InternalMessageInfo

func (m *PublicKey) GetE() string {
	if m != nil {
		return m.E
	}
	return ""
}

func (m *PublicKey) GetN() string {
	if m != nil {
		return m.N
	}
	return ""
}

type SharedKey struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Cipher               *Cipher  `protobuf:"bytes,2,opt,name=cipher,proto3" json:"cipher,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharedKey) Reset()         { *m = SharedKey{} }
func (m *SharedKey) String() string { return proto.CompactTextString(m) }
func (*SharedKey) ProtoMessage()    {}
func (*SharedKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebceca9e8703e37f, []int{1}
}

func (m *SharedKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharedKey.Unmarshal(m, b)
}
func (m *SharedKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharedKey.Marshal(b, m, deterministic)
}
func (m *SharedKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharedKey.Merge(m, src)
}
func (m *SharedKey) XXX_Size() int {
	return xxx_messageInfo_SharedKey.Size(m)
}
func (m *SharedKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SharedKey.DiscardUnknown(m)
}

var xxx_messageInfo_SharedKey proto.InternalMessageInfo

func (m *SharedKey) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SharedKey) GetCipher() *Cipher {
	if m != nil {
		return m.Cipher
	}
	return nil
}

type Cipher struct {
	IV                   []byte   `protobuf:"bytes,1,opt,name=IV,proto3" json:"IV,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cipher) Reset()         { *m = Cipher{} }
func (m *Cipher) String() string { return proto.CompactTextString(m) }
func (*Cipher) ProtoMessage()    {}
func (*Cipher) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebceca9e8703e37f, []int{2}
}

func (m *Cipher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cipher.Unmarshal(m, b)
}
func (m *Cipher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cipher.Marshal(b, m, deterministic)
}
func (m *Cipher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cipher.Merge(m, src)
}
func (m *Cipher) XXX_Size() int {
	return xxx_messageInfo_Cipher.Size(m)
}
func (m *Cipher) XXX_DiscardUnknown() {
	xxx_messageInfo_Cipher.DiscardUnknown(m)
}

var xxx_messageInfo_Cipher proto.InternalMessageInfo

func (m *Cipher) GetIV() []byte {
	if m != nil {
		return m.IV
	}
	return nil
}

func (m *Cipher) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type CipherTicket struct {
	ID                   []byte   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Cipher               *Cipher  `protobuf:"bytes,2,opt,name=cipher,proto3" json:"cipher,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CipherTicket) Reset()         { *m = CipherTicket{} }
func (m *CipherTicket) String() string { return proto.CompactTextString(m) }
func (*CipherTicket) ProtoMessage()    {}
func (*CipherTicket) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebceca9e8703e37f, []int{3}
}

func (m *CipherTicket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CipherTicket.Unmarshal(m, b)
}
func (m *CipherTicket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CipherTicket.Marshal(b, m, deterministic)
}
func (m *CipherTicket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CipherTicket.Merge(m, src)
}
func (m *CipherTicket) XXX_Size() int {
	return xxx_messageInfo_CipherTicket.Size(m)
}
func (m *CipherTicket) XXX_DiscardUnknown() {
	xxx_messageInfo_CipherTicket.DiscardUnknown(m)
}

var xxx_messageInfo_CipherTicket proto.InternalMessageInfo

func (m *CipherTicket) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *CipherTicket) GetCipher() *Cipher {
	if m != nil {
		return m.Cipher
	}
	return nil
}

type Client struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	AliasName            string   `protobuf:"bytes,3,opt,name=aliasName,proto3" json:"aliasName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebceca9e8703e37f, []int{4}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Client) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Client) GetAliasName() string {
	if m != nil {
		return m.AliasName
	}
	return ""
}

type Ticket struct {
	Address              string        `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	SecretKey            string        `protobuf:"bytes,2,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	ClientTicket         *ClientTicket `protobuf:"bytes,3,opt,name=clientTicket,proto3" json:"clientTicket,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Ticket) Reset()         { *m = Ticket{} }
func (m *Ticket) String() string { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()    {}
func (*Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebceca9e8703e37f, []int{5}
}

func (m *Ticket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ticket.Unmarshal(m, b)
}
func (m *Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ticket.Marshal(b, m, deterministic)
}
func (m *Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket.Merge(m, src)
}
func (m *Ticket) XXX_Size() int {
	return xxx_messageInfo_Ticket.Size(m)
}
func (m *Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket proto.InternalMessageInfo

func (m *Ticket) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Ticket) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *Ticket) GetClientTicket() *ClientTicket {
	if m != nil {
		return m.ClientTicket
	}
	return nil
}

type ClientTicket struct {
	ConnID               string   `protobuf:"bytes,1,opt,name=connID,proto3" json:"connID,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientTicket) Reset()         { *m = ClientTicket{} }
func (m *ClientTicket) String() string { return proto.CompactTextString(m) }
func (*ClientTicket) ProtoMessage()    {}
func (*ClientTicket) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebceca9e8703e37f, []int{6}
}

func (m *ClientTicket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientTicket.Unmarshal(m, b)
}
func (m *ClientTicket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientTicket.Marshal(b, m, deterministic)
}
func (m *ClientTicket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientTicket.Merge(m, src)
}
func (m *ClientTicket) XXX_Size() int {
	return xxx_messageInfo_ClientTicket.Size(m)
}
func (m *ClientTicket) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientTicket.DiscardUnknown(m)
}

var xxx_messageInfo_ClientTicket proto.InternalMessageInfo

func (m *ClientTicket) GetConnID() string {
	if m != nil {
		return m.ConnID
	}
	return ""
}

func (m *ClientTicket) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Letter struct {
	Type                 Letter_Type `protobuf:"varint,1,opt,name=type,proto3,enum=gschub.Letter_Type" json:"type,omitempty"`
	Receiver             string      `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Data                 []byte      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Letter) Reset()         { *m = Letter{} }
func (m *Letter) String() string { return proto.CompactTextString(m) }
func (*Letter) ProtoMessage()    {}
func (*Letter) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebceca9e8703e37f, []int{7}
}

func (m *Letter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Letter.Unmarshal(m, b)
}
func (m *Letter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Letter.Marshal(b, m, deterministic)
}
func (m *Letter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Letter.Merge(m, src)
}
func (m *Letter) XXX_Size() int {
	return xxx_messageInfo_Letter.Size(m)
}
func (m *Letter) XXX_DiscardUnknown() {
	xxx_messageInfo_Letter.DiscardUnknown(m)
}

var xxx_messageInfo_Letter proto.InternalMessageInfo

func (m *Letter) GetType() Letter_Type {
	if m != nil {
		return m.Type
	}
	return Letter_Single
}

func (m *Letter) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *Letter) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Reply struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	HMAC                 []byte   `protobuf:"bytes,2,opt,name=HMAC,proto3" json:"HMAC,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp            int32    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ebceca9e8703e37f, []int{8}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Reply) GetHMAC() []byte {
	if m != nil {
		return m.HMAC
	}
	return nil
}

func (m *Reply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Reply) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("gschub.Letter_Type", Letter_Type_name, Letter_Type_value)
	proto.RegisterType((*PublicKey)(nil), "gschub.PublicKey")
	proto.RegisterType((*SharedKey)(nil), "gschub.SharedKey")
	proto.RegisterType((*Cipher)(nil), "gschub.Cipher")
	proto.RegisterType((*CipherTicket)(nil), "gschub.CipherTicket")
	proto.RegisterType((*Client)(nil), "gschub.Client")
	proto.RegisterType((*Ticket)(nil), "gschub.Ticket")
	proto.RegisterType((*ClientTicket)(nil), "gschub.ClientTicket")
	proto.RegisterType((*Letter)(nil), "gschub.Letter")
	proto.RegisterType((*Reply)(nil), "gschub.Reply")
}

func init() { proto.RegisterFile("message/message.proto", fileDescriptor_ebceca9e8703e37f) }

var fileDescriptor_ebceca9e8703e37f = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4b, 0x6b, 0xdb, 0x40,
	0x10, 0xae, 0x6c, 0x79, 0x1b, 0x4d, 0x84, 0x11, 0xdb, 0xb4, 0x88, 0xd2, 0x43, 0xd0, 0xa1, 0xc9,
	0xa1, 0xb8, 0xe0, 0x5c, 0x7a, 0xe8, 0xa5, 0x38, 0x6e, 0x1b, 0x92, 0x9a, 0xb0, 0x09, 0xb9, 0xaf,
	0xa5, 0xc1, 0x5e, 0xac, 0x17, 0xbb, 0xeb, 0x82, 0xfa, 0x43, 0xfa, 0x7b, 0xcb, 0x3e, 0x2c, 0xab,
	0x90, 0x43, 0x4e, 0xda, 0x6f, 0xe6, 0x7b, 0xcc, 0x68, 0x17, 0xde, 0x56, 0xa8, 0x14, 0xdf, 0xe0,
	0x67, 0xff, 0x9d, 0xb5, 0xb2, 0xd1, 0x0d, 0x25, 0x1b, 0x95, 0x6f, 0xf7, 0xeb, 0xec, 0x02, 0xa2,
	0xfb, 0xfd, 0xba, 0x14, 0xf9, 0x2d, 0x76, 0x34, 0x86, 0x60, 0x99, 0x06, 0xe7, 0xc1, 0x65, 0xc4,
	0x82, 0xa5, 0x41, 0xab, 0x74, 0xe4, 0xd0, 0x2a, 0x5b, 0x42, 0xf4, 0xb0, 0xe5, 0x12, 0x0b, 0x43,
	0x4c, 0x60, 0xbc, 0xc3, 0xce, 0x52, 0x63, 0x66, 0x8e, 0xf4, 0x23, 0x90, 0x5c, 0xb4, 0x5b, 0x94,
	0x56, 0x71, 0x3a, 0x9f, 0xce, 0x5c, 0xc0, 0x6c, 0x61, 0xab, 0xcc, 0x77, 0xb3, 0x4f, 0x40, 0x5c,
	0x85, 0x4e, 0x61, 0x74, 0xf3, 0xe4, 0x2d, 0x46, 0x37, 0x4f, 0x94, 0x42, 0x58, 0x70, 0xcd, 0xad,
	0x3e, 0x66, 0xf6, 0x9c, 0x7d, 0x87, 0xd8, 0xb1, 0x1f, 0x45, 0xbe, 0x43, 0x6d, 0x35, 0xd7, 0xbd,
	0xe6, 0xfa, 0xc5, 0xa9, 0x77, 0x40, 0x16, 0xa5, 0xc0, 0x7a, 0xe8, 0x10, 0x59, 0x87, 0x33, 0x98,
	0xe8, 0x66, 0x87, 0xb5, 0x5f, 0xd4, 0x01, 0xfa, 0x01, 0x22, 0x5e, 0x0a, 0xae, 0x56, 0xbc, 0xc2,
	0x74, 0x6c, 0x3b, 0xc7, 0x42, 0xf6, 0x07, 0x88, 0x9f, 0x27, 0x85, 0xd7, 0xbc, 0x28, 0x24, 0x2a,
	0xe5, 0x2d, 0x0f, 0xd0, 0x38, 0x28, 0xcc, 0x25, 0xea, 0x5b, 0xec, 0xbc, 0xf7, 0xb1, 0x40, 0xbf,
	0x40, 0x9c, 0xdb, 0x79, 0x9c, 0x8f, 0x8d, 0x38, 0x9d, 0x9f, 0xf5, 0xd3, 0x0f, 0x7a, 0xec, 0x3f,
	0x66, 0xf6, 0x15, 0xe2, 0x61, 0x97, 0xbe, 0x03, 0x92, 0x37, 0x75, 0xdd, 0xef, 0xe4, 0xd1, 0xf3,
	0x7b, 0x65, 0x7f, 0x03, 0x20, 0x77, 0xa8, 0x35, 0x4a, 0x7a, 0x01, 0xa1, 0xee, 0x5a, 0xb4, 0xb2,
	0xe9, 0xfc, 0xcd, 0x21, 0xda, 0x75, 0x67, 0x8f, 0x5d, 0x8b, 0xcc, 0x12, 0xe8, 0x7b, 0x38, 0x91,
	0x98, 0xa3, 0xf8, 0xed, 0xff, 0x72, 0xc4, 0x7a, 0xdc, 0xdf, 0xd9, 0x78, 0x70, 0x67, 0x57, 0x10,
	0x1a, 0x35, 0x05, 0x20, 0x0f, 0xa2, 0xde, 0x94, 0x98, 0xbc, 0xa2, 0x11, 0x4c, 0x7e, 0xc8, 0x66,
	0xdf, 0x26, 0x01, 0x3d, 0x81, 0xf0, 0x5e, 0xd4, 0x9b, 0x64, 0x64, 0x08, 0x0c, 0x6b, 0x5e, 0x61,
	0x32, 0xce, 0x10, 0x26, 0x0c, 0xdb, 0xb2, 0x33, 0xfb, 0x28, 0xac, 0x0b, 0x94, 0x87, 0x7d, 0x1c,
	0x32, 0x49, 0x3f, 0x7f, 0x7d, 0x5b, 0x1c, 0x5e, 0x87, 0x39, 0x3f, 0x97, 0x6e, 0xfe, 0xbb, 0x16,
	0x15, 0x2a, 0xcd, 0xab, 0x36, 0x0d, 0xcf, 0x83, 0xcb, 0x09, 0x3b, 0x16, 0xd6, 0xc4, 0x3e, 0xfe,
	0xab, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x41, 0x5d, 0x65, 0xe3, 0x15, 0x03, 0x00, 0x00,
}
